### ISSUE TITLE
Failed to Build on Heroku

### ISSUE THREAD

**Issue by xuejimmy** [pkcwong/meteor-react-starter#28]
```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> meteor app detected
remote: 
remote: -----> Moving app source into a subdirectory
remote: 
remote:        Node engine:         0.10.40
remote:        Npm engine:          unspecified
remote:        Start mechanism:     none
remote:        node_modules source: none
remote:        node_modules cached: false
remote: 
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_MODULES_CACHE=true
remote: 
remote:        PRO TIP: Use 'npm init' and 'npm install --save' to define dependencies
remote:        See https://devcenter.heroku.com/articles/nodejs-support
remote: 
remote:        PRO TIP: Include a Procfile, package.json start script, or server.js file to start your app
remote:        See https://devcenter.heroku.com/articles/nodejs-support#runtime-behavior
remote: 
remote: -----> Installing binaries
remote:        Downloading and installing node 0.10.40...
remote: 
remote: -----> Building dependencies
remote:        Skipping dependencies (no source for node_modules)
remote: 
remote: -----> Checking startup method
remote: 
remote: -----> Finalizing build
remote:        Creating runtime environment
remote:        Exporting binary paths
remote:        Cleaning up build artifacts
remote:        Build successful!
remote:        /tmp/build_3cd55c27749d4d8e53feccc640e5392d
remote:        └── (empty)
remote:        
remote: 
remote: -----> Fetching Meteor 1.7.0.3
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--remote:   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--remote:   0  173M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--remote:  10  173M   10 18.3M    0     0  7756k      0  0:00:22  0:00:02  0:00:20remote:  36  173M   36 63.9M    0     0  18.5M      0  0:00:09  0:00:03  0:00:06remote:  69  173M   69  119M    0     0  27.0M      0  0:00:06  0:00:04  0:00:02remote: 100  173M  100  173M    0     0  32.7M      0  0:00:05  0:00:05 --:--:-- 42.6M
remote: 
remote: -----> Unpacking Meteor 1.7.0.3
remote:        Meteor 1.7.0.3 is installed
remote: 
remote: -----> Building Meteor App Bundle
remote:        WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
remote:         - postcss@^6.0.22 not installed.
remote:         - postcss-load-config@^1.2.0 not installed.
remote:        
remote:        Read more about installing npm peer dependencies:
remote:          http://guide.meteor.com/using-packages.html#peer-npm-dependencies
remote:        
remote:        Errors prevented bundling:
remote:        While loading plugin `minifier-postcss` from package `juliancwirko:postcss`:
remote:        packages/modules-runtime.js:231:12: Cannot find module 'postcss'
remote:        at makeMissingError (packages/modules-runtime.js:231:12)
remote:        at require (packages/modules-runtime.js:241:19)
remote:        at minify-css.js (packages/minifier-postcss/plugin/minify-css.js:16:15)
remote:        at fileEvaluate (packages/modules-runtime.js:343:9)
remote:        at require (packages/modules-runtime.js:238:16)
remote:        at <runJavaScript-23>:279:1
remote:        at <runJavaScript-23>:284:3
remote:        
remote:        
remote: 
remote: -----> Installing App's NPM Dependencies
remote: /app/tmp/buildpacks/48bbcd8a1f2d1885ea7beef562aaaa72c82d8575e00fec23e8342bcc96a462c83fe9b01b1c05c977c72a3e06a800ba84ace0a00796dcb33135260c214066cb33/bin/compile_meteor: line 66: cd: ../build/bundle/programs/server: No such file or directory
remote:  !     Push rejected, failed to compile meteor app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to jimmyxue.
remote: 
To https://git.heroku.com/jimmyxue.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/jimmyxue.git'

```

**Comment by pkcwong** [comment]
should be fixed
